# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UFPRCampusMap
                                 A QGIS plugin
 This plugin makes an schematic map for indoor environments.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-12-13
        copyright            : (C) 2019 by Luiz Otávio Carneiro Filho
        email                : luiizot@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Luiz Otávio Carneiro Filho'
__date__ = '2019-12-13'
__copyright__ = '(C) 2019 by Luiz Otávio Carneiro Filho'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UFPRCampusMap class from file UFPRCampusMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indoor_schematic import UFPRCampusMapPlugin
    return UFPRCampusMapPlugin()
